name: vistoria
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  permission_handler: ^10.2.0
  cupertino_icons: ^1.0.2
  emailjs: ^1.1.0
  brasil_fields: ^1.5.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.1.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  url_launcher: ^6.1.6
  firebase_storage: ^11.0.6
  intl: ^0.17.0
  image_picker: ^0.8.3+1
  flutter_launcher_icons: ^0.8.0
  geolocator: ^9.0.1
  path_provider: ^2.0.11
  share_extend: ^2.0.0
  flutter_full_pdf_viewer: ^1.0.6

  pdf: ^1.13.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter_icons:
  android: true
  image_path: "assets/image/logo_light.png"


flutter:

  uses-material-design: true


  assets:
   - assets/image/



  fonts:
     - family: Nunito
       fonts:
         - asset: assets/fonts/Nunito-Regular.ttf
